### ISSUE TITLE
Get file from remote server

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#14]
- [x] user input file name
- [x] validate file exists
- [x] if file does not exist, error handling
- [x] user input / validate input
- [x] transfer file from source to destination
