### ISSUE TITLE
Put file onto remote server

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#29]
- [x] User input file name / path
- [x] Validate that name does not exist
- [x] If file does not exist, error handling
- [x] User input / validate destination
- [x] Transfer file from source to destination
