### ISSUE TITLE
Create a directory on remote server

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#42]
- [x] Valid user input
- [x] Check if file exists
- [x] Create new directory
- [x] Error handling

**Comment by SoySauceLabs** [comment]
Tested and looks good!
