### ISSUE TITLE
Rename file on local machine

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#51]
- [ ] Validate user input
- [ ] Check if file exists
- [ ] Change local file name
- [ ] Save file on local
- [ ] Error handling
