### ISSUE TITLE
Rename file on remote server

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#56]
- [ ] Validate user input
- [ ] Check if file exists
- [ ] Change file name
- [ ] Save file on server
- [ ] Error handling
