### ISSUE TITLE
Delete directories on remote server

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#63]
- [ ]  User input directory name
- [ ]  Validate directory exists
- [ ]  Error handle if directory does not exist
- [ ]  Validate user input & destination
- [ ]  Delete directory on remote server
