### ISSUE TITLE
Copy directories from local to remote server

### ISSUE THREAD

**Issue by stripes416** [Agile410/FTPizza#69]
- [ ]  User input directory name
- [ ]  Validate directory exists
- [ ]  Error handle if directory does not exist
- [ ]  Validate user input & destination
- [ ]  Transfer directory from source to remote server
